### ISSUE TITLE
arithmetic operations

### ISSUE THREAD

**Issue by nikita-moor** [andreas50/uts#2]
When I add or subtract time-series, I expect they will be interpolated in every time-step, but it is not so. Is it correct behavior or I'm doing something wrong?

![arithmetic](https://user-images.githubusercontent.com/13879891/85933151-857b7d00-b8dc-11ea-91fb-9936b4ab6222.png)

```r
library(uts)

a <- uts(
  values = c(1, 2, 3),
  times = c("2000-01-01", "2000-01-02", "2000-01-03")
)
b <- uts(
  values = c(-1, +1),
  times = c("2000-01-01", "2000-01-03")
)

plot(a, ylim=range(-5, 5))
lines(b$times, b$values)
points(a$times, a$values)
points(b$times, b$values)

ab_sum <- a+b
lines(ab_sum$times, ab_sum$values, col="red")

ab_dif <- a-b
lines(ab_dif$times, ab_dif$values, col="green")

```

**Comment by andreas50** [comment]
By default, the "+" and "-" function of the package use last-point instead of linear interpolation for time series arithmetic. Behind the scenes, these functions call binary_Ops(), which does allow to specify the interpolation method. For example:

binary_Ops(a, "+", b)
binary_Ops(a, "+", b, interpolation="linear")

Please install the latest version of the package for the code to work.
